platform :ios, ‘8.0’
source ‘https://github.com/CocoaPods/Specs.git’
source ‘https://github.com/losehero/PSPecs.git'

 target 'LBaseProject' do
	pod	'YTKNetwork', '~> 2.0.1’
	pod	'SDWebImage', '~>3.8'
	pod	'UMengAnalytics'
	pod	'HomeViewProject', '0.0.3'
    pod 'Objection', '1.6.1'
 end


